package io.github.xiwei753.pinyin.t9.core

import io.github.xiwei753.pinyin.t9.data.DictionaryProvider
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class T9EngineTest {

    class MockDict : DictionaryProvider {
    override fun getPinyinExactCandidatesMultiple(pinyinSequences: List<String>): Map<String, List<Candidate>> {
        val result = mutableMapOf<String, List<Candidate>>()
        for (seq in pinyinSequences) {
            result[seq] = list.filter { it.code == seq }
        }
        return result
    }
        private val list = mutableListOf<Candidate>()

        fun add(c: Candidate, pinyin: String) {
            val origin = if (c.text.length == 1) CandidateOrigin.EXACT_SINGLE else CandidateOrigin.EXACT_PHRASE
            list.add(Candidate(c.text, pinyin, c.score, c.type, "", origin))
        }

        override fun getPinyinExactCandidates(pinyinSequence: String): List<Candidate> {
            return list.filter { it.code == pinyinSequence }
        }

        override fun getPinyinPrefixCandidates(pinyinPrefix: String): List<Candidate> {
            return list.filter { it.code.startsWith(pinyinPrefix) }
        }

        override fun getSingleSyllableCandidates(syllable: String): List<Candidate> {
            return list.filter { it.code == syllable }
        }

        override fun getCandidates(code: String): List<Candidate> = emptyList()
        override fun getExactCandidates(code: String): List<Candidate> = emptyList()
        override fun getPrefixCandidates(code: String): List<Candidate> = emptyList()
    }

    @Test
    fun testCandidateLimitCaching() {
        val dict = MockDict()
        for (i in 1..20) {
            dict.add(Candidate("测$i", "28", 1000 - i, CandidateType.SINGLE_CHAR), "bu")
        }

        val engine = T9Engine(dict)
        engine.inputDigit("2")
        engine.inputDigit("8")

        // Test 1: getPreedit() shouldn't pollute cache with 30 candidates
        val preedit = engine.getPreedit()
        assertEquals("bu", preedit)
        var cands = engine.getCandidates(5)
        assertTrue(cands.size <= 5)

        engine.clear()
        engine.inputDigit("2")
        engine.inputDigit("8")

        // Test 2: changing from larger to smaller limit
        cands = engine.getCandidates(30)
        assertTrue(cands.size > 5)
        cands = engine.getCandidates(5)
        assertTrue(cands.size <= 5)

        engine.clear()
        engine.inputDigit("2")
        engine.inputDigit("8")

        // Test 3: changing from smaller to larger limit
        cands = engine.getCandidates(5)
        assertTrue(cands.size <= 5)
        cands = engine.getCandidates(10)
        assertTrue(cands.size > 5)
        assertTrue(cands.size <= 10)
    }

    @Test
    fun testPreeditSourceSyncWithoutCache() {
        val dict = MockDict()
        dict.add(Candidate("周", "9468", 100000, CandidateType.SINGLE_CHAR), "zhou")
        dict.add(Candidate("字母", "9468", 90000, CandidateType.NORMAL), "zi mu")

        val engine = T9Engine(dict)
        engine.inputDigit("9")
        engine.inputDigit("4")
        engine.inputDigit("6")
        engine.inputDigit("8")

        // Call getPreedit() first to ensure it computes correctly without an existing limit cache
        val preedit = engine.getPreedit()

        // Then call getCandidates() with a small limit
        val cands = engine.getCandidates(5)

        // Preedit must be strictly generated by decoding, decoupling from first candidate
        assertEquals("zhou", preedit)

        // Cache must not be polluted, limit should be respected
        assertTrue(cands.size <= 5)
    }

    @Test
    fun testPreedit() {
        val dict = MockDict()
        val engine = T9Engine(dict)

        engine.inputDigit("2")
        engine.inputDigit("8")
        assertEquals("bu", engine.getPreedit())

        engine.inputDigit("8")
        engine.inputDigit("2")
        engine.inputDigit("4")
        assertEquals("bu tai", engine.getPreedit())

        engine.inputDigit("9")
        engine.inputDigit("4")
        engine.inputDigit("6")
        engine.inputDigit("4")
        assertEquals("bu tai xing", engine.getPreedit())

        engine.clear()

        // Test jin tian wan shang
        val digits = "546842692674264"
        for (d in digits) {
            engine.inputDigit(d.toString())
        }
        assertEquals("jin tian wan shang", engine.getPreedit())
    }

    @Test
    fun testSeparator() {
        val dict = MockDict()
        val engine = T9Engine(dict)

        engine.inputDigit("2")
        engine.inputDigit("8")
        engine.inputDigit("1")
        engine.inputDigit("8")
        engine.inputDigit("2")
        engine.inputDigit("4")
        assertEquals("bu tai", engine.getPreedit())

        engine.clear()

        val sepDigits = "28182419464"
        for (d in sepDigits) {
            engine.inputDigit(d.toString())
        }
        assertEquals("bu tai xing", engine.getPreedit())

        // Test backspacing separator updates preedit
        engine.backspace() // removes '4'
        engine.backspace() // removes '6'
        engine.backspace() // removes '4'
        engine.backspace() // removes '9'
        engine.backspace() // removes '1'
        assertEquals("bu tai", engine.getPreedit())
    }

    @Test
    fun testFallback() {
        val dict = MockDict()
        val engine = T9Engine(dict)
        engine.inputDigit("2")
        engine.inputDigit("8")
        val cands = engine.getCandidates()
        assertEquals("28", cands.last().text)
    }

    @Test
    fun testSingleCharactersMustBePresent() {
        val dict = MockDict()
        dict.add(Candidate("我", "96", 100000, CandidateType.SINGLE_CHAR), "wo")
        dict.add(Candidate("你", "64", 90000, CandidateType.SINGLE_CHAR), "ni")
        dict.add(Candidate("他", "82", 80000, CandidateType.SINGLE_CHAR), "ta")
        dict.add(Candidate("她", "82", 80000, CandidateType.SINGLE_CHAR), "ta")
        dict.add(Candidate("的", "33", 100000, CandidateType.SINGLE_CHAR), "de")
        dict.add(Candidate("得", "33", 90000, CandidateType.SINGLE_CHAR), "de")
        dict.add(Candidate("地", "33", 80000, CandidateType.SINGLE_CHAR), "de")
        dict.add(Candidate("不", "28", 100000, CandidateType.SINGLE_CHAR), "bu")
        dict.add(Candidate("是", "744", 100000, CandidateType.SINGLE_CHAR), "shi")
        dict.add(Candidate("不太", "28824", 40000, CandidateType.NORMAL), "bu tai")

        val engine = T9Engine(dict)

        // 96 -> 我
        engine.inputDigit("9")
        engine.inputDigit("6")
        assertTrue(engine.getVisibleCandidates().any { it.text == "我" })
        assertEquals("wo", engine.getPreedit())
        engine.clear()

        // 64 -> 你
        engine.inputDigit("6")
        engine.inputDigit("4")
        assertTrue(engine.getVisibleCandidates().any { it.text == "你" })
        assertEquals("ni", engine.getPreedit())
        engine.clear()

        // 82 -> 他/她
        engine.inputDigit("8")
        engine.inputDigit("2")
        assertTrue(engine.getVisibleCandidates().any { it.text == "他" })
        assertTrue(engine.getVisibleCandidates().any { it.text == "她" })
        engine.clear()

        // 33 -> 的/得/地
        engine.inputDigit("3")
        engine.inputDigit("3")
        assertTrue(engine.getVisibleCandidates().any { it.text == "的" })
        assertTrue(engine.getVisibleCandidates().any { it.text == "得" })
        assertTrue(engine.getVisibleCandidates().any { it.text == "地" })
        assertEquals("de", engine.getPreedit())
        engine.clear()

        // 744 -> 是
        engine.inputDigit("7")
        engine.inputDigit("4")
        engine.inputDigit("4")
        assertTrue(engine.getCandidates().any { it.text == "是" })
        engine.clear()

        // 28 -> 不
        engine.inputDigit("2")
        engine.inputDigit("8")
        assertTrue(engine.getCandidates().any { it.text == "不" })
        engine.clear()

        // 28824 -> 不太
        engine.inputDigit("2")
        engine.inputDigit("8")
        engine.inputDigit("8")
        engine.inputDigit("2")
        engine.inputDigit("4")
        assertTrue(engine.getCandidates().any { it.text == "不太" })
        engine.clear()
    }

    @Test
    fun testShortAmbiguousPath() {
        val dict = MockDict()
        dict.add(Candidate("周", "9468", 100000, CandidateType.SINGLE_CHAR), "zhou")
        dict.add(Candidate("字母", "9468", 90000, CandidateType.NORMAL), "zi mu")
        // These are low quality dynamic phrases that could be constructed but should be penalized
        dict.add(Candidate("一", "94", 80000, CandidateType.SINGLE_CHAR), "yi")
        dict.add(Candidate("母", "68", 80000, CandidateType.SINGLE_CHAR), "mu")
        dict.add(Candidate("木", "68", 80000, CandidateType.SINGLE_CHAR), "mu")
        dict.add(Candidate("目", "68", 80000, CandidateType.SINGLE_CHAR), "mu")
        dict.add(Candidate("怒", "68", 80000, CandidateType.SINGLE_CHAR), "nu")
        dict.add(Candidate("榜", "68", 80000, CandidateType.SINGLE_CHAR), "mu") // Just for test

        // Add some more valid candidates to fill the top 5
        dict.add(Candidate("猪", "9468", 70000, CandidateType.SINGLE_CHAR), "zhou")
        dict.add(Candidate("轴", "9468", 60000, CandidateType.SINGLE_CHAR), "zhou")
        dict.add(Candidate("昼", "9468", 50000, CandidateType.SINGLE_CHAR), "zhou")
        dict.add(Candidate("肘", "9468", 40000, CandidateType.SINGLE_CHAR), "zhou")

        val engine = T9Engine(dict)
        engine.inputDigit("9")
        engine.inputDigit("4")
        engine.inputDigit("6")
        engine.inputDigit("8")

        val cands = engine.getCandidates()
        val preedit = engine.getPreedit()

        assertTrue(cands.any { it.text == "周" } || cands.any { it.text == "字母" })
        assertTrue(cands[0].text == "周" || cands[0].text == "字母")

        // Verify decoupling
        assertEquals("zhou", preedit)

        val topCandsText = cands.take(5).map { it.text }

        assertTrue("一母" !in topCandsText)
        assertTrue("一 母" !in topCandsText)
        assertTrue("一木" !in topCandsText)
        assertTrue("一 木" !in topCandsText)
        assertTrue("一目" !in topCandsText)
        assertTrue("一 目" !in topCandsText)
        assertTrue("一怒" !in topCandsText)
        assertTrue("一 怒" !in topCandsText)
        assertTrue("一榜" !in topCandsText)
        assertTrue("一 榜" !in topCandsText)
    }

    @Test
    fun testCandidateDisplayAndCommitHasNoSpaces() {
        val dict = MockDict()
        // High scores so they become candidates
        dict.add(Candidate("一", "94", 80000, CandidateType.SINGLE_CHAR), "yi")
        dict.add(Candidate("母", "68", 80000, CandidateType.SINGLE_CHAR), "mu")

        val engine = T9Engine(dict)
        engine.inputDigit("9")
        engine.inputDigit("4")
        engine.inputDigit("6")
        engine.inputDigit("8")

        val cands = engine.getCandidates()
        // Text shouldn't have space, except in DYNAMIC_COMPOSITION where it's retained internally
        // But visible candidates won't contain DYNAMIC_COMPOSITION.
        val visible = engine.getVisibleCandidates()
        assertTrue(visible.none { it.text == "一 母" })
        assertTrue(visible.none { it.text == "一母" })

        // Find if any internal candidate is "一 母", and commit it
        val cand = cands.find { it.text == "一 母" }
        if (cand != null) {
            val committed = engine.commitCandidate(cand)
            // It should NOT replace spaces
            assertEquals("一 母", committed.text)
        }
    }

    @Test
    fun testCandidateOriginLogic() {
        val dict = MockDict()
        dict.add(Candidate("一", "94", 80000, CandidateType.SINGLE_CHAR), "yi")
        dict.add(Candidate("母", "68", 80000, CandidateType.SINGLE_CHAR), "mu")
        dict.add(Candidate("一母", "9468", 90000, CandidateType.NORMAL), "yi mu")

        val engine = T9Engine(dict)
        engine.inputDigit("9")
        engine.inputDigit("4")
        engine.inputDigit("6")
        engine.inputDigit("8")

        val visible = engine.getVisibleCandidates()
        // Should only have EXACT_SINGLE or EXACT_PHRASE origins
        assertTrue(visible.all { it.origin == CandidateOrigin.EXACT_SINGLE || it.origin == CandidateOrigin.EXACT_PHRASE })

        // "一母" is exactly from dict, so it should be visible
        assertTrue(visible.any { it.text == "一母" })

        val internal = engine.getCandidates()
        // Should contain dynamic compositions like "一 母"
        val dynamic = internal.find { it.text == "一 母" }
        assertTrue(dynamic != null)
        assertEquals(CandidateOrigin.DYNAMIC_COMPOSITION, dynamic!!.origin)
    }

    @Test
    fun test63MeNeNotMei() {
        val dict = MockDict()
        dict.add(Candidate("么", "me", 10000, CandidateType.SINGLE_CHAR), "me")
        dict.add(Candidate("呢", "ne", 10000, CandidateType.SINGLE_CHAR), "ne")
        dict.add(Candidate("没", "mei", 10000, CandidateType.SINGLE_CHAR), "mei")

        // Add some dynamic items
        dict.add(Candidate("哦", "o", 50000, CandidateType.SINGLE_CHAR), "o")
        dict.add(Candidate("饿", "e", 50000, CandidateType.SINGLE_CHAR), "e")

        val engine = T9Engine(dict)
        engine.inputDigit("6")
        engine.inputDigit("3")

        val visible = engine.getVisibleCandidates()
        assertTrue(visible.none { it.text == "没" })
        assertTrue(visible.any { it.text == "么" })
        assertTrue(visible.any { it.text == "呢" })
        assertTrue(visible.none { it.origin == CandidateOrigin.DYNAMIC_COMPOSITION })
        assertTrue(visible.none { it.text == "哦饿" || it.text == "哦 饿" })
    }

    @Test
    fun test636MenNenNotOEng() {
        val dict = MockDict()
        dict.add(Candidate("门", "men", 10000, CandidateType.SINGLE_CHAR), "men")
        dict.add(Candidate("嫩", "nen", 10000, CandidateType.SINGLE_CHAR), "nen")

        // Add some dynamic items
        dict.add(Candidate("哦", "o", 50000, CandidateType.SINGLE_CHAR), "o")
        dict.add(Candidate("嗯", "eng", 50000, CandidateType.SINGLE_CHAR), "eng")

        val engine = T9Engine(dict)
        engine.inputDigit("6")
        engine.inputDigit("3")
        engine.inputDigit("6")

        val visible = engine.getVisibleCandidates()
        assertTrue(visible.any { it.text == "门" })
        assertTrue(visible.any { it.text == "嫩" })
        assertTrue(visible.none { it.origin == CandidateOrigin.DYNAMIC_COMPOSITION })
        assertTrue(visible.none { it.text == "哦嗯" || it.text == "哦 嗯" })
    }

    @Test
    fun testVisibleCandidatesGate() {
        val dict = MockDict()
        dict.add(Candidate("不", "28", 1000, CandidateType.SINGLE_CHAR), "bu")
        dict.add(Candidate("版权", "2267826", 10000, CandidateType.NORMAL), "ban quan")
        dict.add(Candidate("ban", "226", 9000, CandidateType.NORMAL), "ban")

        val engine = T9Engine(dict)

        // Input length 1
        engine.inputDigit("2")

        // We should add a candidate "版" to test that prefix single-char doesn't get shown for 2
        dict.add(Candidate("版", "226", 8000, CandidateType.SINGLE_CHAR), "ban")

        val visibleCandsLength1 = engine.getVisibleCandidates()
        // Should not have "版权" (multi-char for length 1)
        assertTrue(visibleCandsLength1.none { it.text == "版权" })
        // Should not have "ban" (pinyin)
        assertTrue(visibleCandsLength1.none { it.text == "ban" })
        // Should not have "2" (numeric fallback)
        assertTrue(visibleCandsLength1.none { it.text == "2" })
        // Should not have "版" because its code length > 1
        assertTrue(visibleCandsLength1.none { it.text == "版" })

        // Ensure preedit is not "ban"
        assertTrue(engine.getPreedit() != "ban")

        val internalCandsLength1 = engine.getCandidates()
        // Internal candidates WILL have the numeric fallback
        assertEquals("2", internalCandsLength1.last().text)

        engine.clear()

        // Input length 2
        engine.inputDigit("2")
        engine.inputDigit("8")

        val visibleCandsLength2 = engine.getVisibleCandidates()
        // Should not have "28" (numeric fallback)
        assertTrue(visibleCandsLength2.none { it.text == "28" })
        // "不" should be visible
        assertTrue(visibleCandsLength2.any { it.text == "不" })
    }

    @Test
    fun testShortCandidates() {
        val dict = MockDict()
        dict.add(Candidate("不", "28", 1000, CandidateType.SINGLE_CHAR), "bu")
        dict.add(Candidate("部", "28", 900, CandidateType.SINGLE_CHAR), "bu")
        dict.add(Candidate("不太", "28824", 500, CandidateType.NORMAL), "bu tai")

        val engine = T9Engine(dict)
        engine.inputDigit("2")
        engine.inputDigit("8")

        val cands = engine.getCandidates()
        assertTrue(cands.any { it.text == "不" })
        assertTrue(cands.any { it.text == "部" })
    }

    @Test
    fun testLongSentenceCandidatesNotMatchingRawDigits() {
        val dict = MockDict()
        dict.add(Candidate("不太行", "288249464", 1000, CandidateType.NORMAL), "bu tai xing")
        // This is a word that matches the raw digits but NOT the pinyin sequence bu tai xing
        dict.add(Candidate("不太新股", "288249464", 900, CandidateType.NORMAL), "bu tai xin gu")
        dict.add(Candidate("不太英语", "288249464", 800, CandidateType.NORMAL), "bu tai ying yu")

        val engine = T9Engine(dict)
        engine.inputDigit("2")
        engine.inputDigit("8")
        engine.inputDigit("8")
        engine.inputDigit("2")
        engine.inputDigit("4")
        engine.inputDigit("9")
        engine.inputDigit("4")
        engine.inputDigit("6")
        engine.inputDigit("4")

        val cands = engine.getCandidates()
        assertEquals("不太行", cands[0].text)
        // Should not have 不太新股 or 不太英语
        assertTrue(cands.none { it.text == "不太新股" })
        assertTrue(cands.none { it.text == "不太英语" })
    }


    @Test
    fun testShaShiHou() {
        val dict = MockDict()
        // Provide candidate to match "啥时候" -> sha shi hou
        dict.add(Candidate("啥时候", "742744468", 100000, CandidateType.NORMAL), "sha shi hou")
        // These are dynamic sentence generations in reality, let's pretend they have lower score
        dict.add(Candidate("啥是狗", "742744468", 8000, CandidateType.NORMAL), "sha shi gou")
        dict.add(Candidate("啥是构", "742744468", 7000, CandidateType.NORMAL), "sha shi gou")
        dict.add(Candidate("啥是够", "742744468", 6000, CandidateType.NORMAL), "sha shi gou")

        // Add some dummy ones so we fill the top 5
        dict.add(Candidate("沙石后", "742744468", 90000, CandidateType.NORMAL), "sha shi hou")
        dict.add(Candidate("杀师后", "742744468", 80000, CandidateType.NORMAL), "sha shi hou")
        dict.add(Candidate("刹时后", "742744468", 70000, CandidateType.NORMAL), "sha shi hou")
        dict.add(Candidate("傻事后", "742744468", 60000, CandidateType.NORMAL), "sha shi hou")


        val engine = T9Engine(dict)
        engine.inputDigit("7")
        engine.inputDigit("4")
        engine.inputDigit("2")
        engine.inputDigit("7")
        engine.inputDigit("4")
        engine.inputDigit("4")
        engine.inputDigit("4")
        engine.inputDigit("6")
        engine.inputDigit("8")

        val cands = engine.getCandidates()
        val preedit = engine.getPreedit()

        assertTrue(cands.isNotEmpty())
        assertEquals("啥时候", cands[0].text)
        assertEquals("sha shi hou", preedit)

        val topCandsText = cands.take(5).map { it.text }

        assertTrue("啥是狗" !in topCandsText)
        assertTrue("啥是够" !in topCandsText)
        assertTrue("啥是构" !in topCandsText)
    }

    // ── Candidate layering tests ──

    @Test
    fun testVisibleExactPhraseBeforeSingle() {
        val dict = MockDict()
        // Use an input where both exact phrase AND single chars appear
        // "bu tai" is 2-syllable; "不" comes from prefix single-syllable "bu"
        dict.add(Candidate("不太", "28824", 90000, CandidateType.NORMAL), "bu tai")
        dict.add(Candidate("不", "28", 80000, CandidateType.SINGLE_CHAR), "bu")

        val engine = T9Engine(dict)
        engine.inputDigit("2")
        engine.inputDigit("8")
        engine.inputDigit("8")
        engine.inputDigit("2")
        engine.inputDigit("4")

        val visible = engine.getVisibleCandidates()
        val idxBuTai = visible.indexOfFirst { it.text == "不太" }

        assertTrue("exact phrase 不太 should be visible, got ${visible.map { it.text }}", idxBuTai >= 0)
        val singleIdx = visible.indexOfFirst { it.origin == CandidateOrigin.EXACT_SINGLE }
        if (singleIdx >= 0) {
            assertTrue("exact phrase should appear before any EXACT_SINGLE",
                idxBuTai < singleIdx)
        }
    }

    @Test
    fun testExactPhraseBlocksDynamicComposition() {
        val dict = MockDict()
        // For multi-syllable "bu", mock a complete pinyin that has a phrase
        dict.add(Candidate("不太", "28824", 500, CandidateType.NORMAL), "bu tai")
        dict.add(Candidate("不", "28", 100000, CandidateType.SINGLE_CHAR), "bu")
        dict.add(Candidate("太", "82", 100000, CandidateType.SINGLE_CHAR), "tai")

        val engine = T9Engine(dict)
        engine.inputDigit("2")
        engine.inputDigit("8")
        engine.inputDigit("8")
        engine.inputDigit("2")
        engine.inputDigit("4")

        val visible = engine.getVisibleCandidates()
        // When exact phrase "不太" exists, dynamic composition should NOT appear
        assertTrue("不太 must be in visible", visible.any { it.text == "不太" })
        assertTrue("No SAFE_DYNAMIC_COMPOSITION allowed when exact phrase exists",
            visible.all { it.origin != CandidateOrigin.SAFE_DYNAMIC_COMPOSITION })
    }

    @Test
    fun testDynamicFallbackMaxOneCandidate() {
        val dict = MockDict()
        // Only single chars that HIGH score (so they appear), no exact phrase
        dict.add(Candidate("不", "28", 100000, CandidateType.SINGLE_CHAR), "bu")
        dict.add(Candidate("太", "82", 100000, CandidateType.SINGLE_CHAR), "tai")

        val engine = T9Engine(dict)
        engine.inputDigit("2")
        engine.inputDigit("8")
        engine.inputDigit("8")
        engine.inputDigit("2")
        engine.inputDigit("4")

        val visible = engine.getVisibleCandidates()
        val dynamicCands = visible.filter { it.origin == CandidateOrigin.SAFE_DYNAMIC_COMPOSITION }
        assertTrue("At most 1 dynamic candidate, got ${dynamicCands.size}", dynamicCands.size <= 1)
    }

    @Test
    fun testDynamicCompositionExcludedWhenExactPhraseExists() {
        val dict = MockDict()
        dict.add(Candidate("不太行", "288249464", 1000, CandidateType.NORMAL), "bu tai xing")
        // These digits could be decomposed but all matches are wrong pinyin
        dict.add(Candidate("不太新股", "288249464", 900, CandidateType.NORMAL), "bu tai xin gu")
        dict.add(Candidate("不太英语", "288249464", 800, CandidateType.NORMAL), "bu tai ying yu")

        val engine = T9Engine(dict)
        engine.inputDigit("2")
        engine.inputDigit("8")
        engine.inputDigit("8")
        engine.inputDigit("2")
        engine.inputDigit("4")
        engine.inputDigit("9")
        engine.inputDigit("4")
        engine.inputDigit("6")
        engine.inputDigit("4")

        val visible = engine.getVisibleCandidates()
        assertEquals("第一候选应是不太行", "不太行", visible.firstOrNull()?.text)
        assertTrue("不应出现不太新股", visible.none { it.text == "不太新股" })
        assertTrue("不应出现不太英语", visible.none { it.text == "不太英语" })
    }

    @Test
    fun testExactPhraseFirstRegardlessOfScore() {
        val dict = MockDict()
        // Single char with very high score
        dict.add(Candidate("不", "28", 999999, CandidateType.SINGLE_CHAR), "bu")
        // Exact phrase with much lower score
        dict.add(Candidate("不太", "28824", 500, CandidateType.NORMAL), "bu tai")

        val engine = T9Engine(dict)
        engine.inputDigit("2")
        engine.inputDigit("8")
        engine.inputDigit("8")
        engine.inputDigit("2")
        engine.inputDigit("4")

        val visible = engine.getVisibleCandidates()
        val idxPhrase = visible.indexOfFirst { it.text == "不太" }

        assertTrue("exact phrase 不太 should be visible, got ${visible.map { it.text }}", idxPhrase >= 0)
        val firstSingleIdx = visible.indexOfFirst { it.origin == CandidateOrigin.EXACT_SINGLE }
        if (firstSingleIdx >= 0) {
            assertTrue("exact phrase (score=500) should appear before first EXACT_SINGLE",
                idxPhrase < firstSingleIdx)
        }
    }

    @Test
    fun testDynamicCandidateLimitedToOne() {
        val dict = MockDict()
        // Only single chars that could form phrases (high score)
        dict.add(Candidate("不", "28", 100000, CandidateType.SINGLE_CHAR), "bu")
        dict.add(Candidate("太", "82", 100000, CandidateType.SINGLE_CHAR), "tai")
        dict.add(Candidate("好", "46", 100000, CandidateType.SINGLE_CHAR), "hao")

        val engine = T9Engine(dict)
        engine.inputDigit("2")
        engine.inputDigit("8")
        engine.inputDigit("8")
        engine.inputDigit("2")
        engine.inputDigit("4")

        val visible = engine.getVisibleCandidates()
        // Dynamic candidates should be at most 1
        val dynamicCount = visible.count { it.origin == CandidateOrigin.SAFE_DYNAMIC_COMPOSITION }
        assertTrue("dynamic candidate count should be <= 1, got $dynamicCount", dynamicCount <= 1)
    }

    @Test
    fun testRawFallbackNotInVisibleCandidates() {
        val dict = MockDict()
        // No candidates at all for "28" (empty dict)
        val engine = T9Engine(dict)
        engine.inputDigit("2")
        engine.inputDigit("8")

        val visible = engine.getVisibleCandidates()
        assertTrue("visible must not contain RAW_FALLBACK",
            visible.none { it.origin == CandidateOrigin.RAW_FALLBACK })

        val internal = engine.getCandidates()
        assertTrue("internal getCandidates must still contain RAW_FALLBACK",
            internal.any { it.origin == CandidateOrigin.RAW_FALLBACK || it.text == "28" })
    }

    @Test
    fun testVisibleOrderByLayerNotByScore() {
        val dict = MockDict()
        // Exact phrase with very low score
        dict.add(Candidate("不太", "28824", 1, CandidateType.NORMAL), "bu tai")
        // Single chars with extremely high score
        dict.add(Candidate("不", "28", 999999, CandidateType.SINGLE_CHAR), "bu")
        dict.add(Candidate("部", "28", 999999, CandidateType.SINGLE_CHAR), "bu")

        val engine = T9Engine(dict)
        engine.inputDigit("2")
        engine.inputDigit("8")
        engine.inputDigit("8")
        engine.inputDigit("2")
        engine.inputDigit("4")

        val visible = engine.getVisibleCandidates()
        val idxPhrase = visible.indexOfFirst { it.text == "不太" }
        val firstSingleIdx = visible.indexOfFirst { it.origin == CandidateOrigin.EXACT_SINGLE }

        assertTrue("exact phrase 不太 must be visible", idxPhrase >= 0)
        if (firstSingleIdx >= 0) {
            assertTrue("exact phrase (score=1) must appear before EXACT_SINGLE (score=999999)",
                idxPhrase < firstSingleIdx)
        }
    }

    @Test
    fun testExactSingleHighScoreDoesNotCrowdOutPhrase() {
        val dict = MockDict()
        // Single char with extremely high score, for multi-syllable input
        dict.add(Candidate("不", "28", 999999, CandidateType.SINGLE_CHAR), "bu")
        dict.add(Candidate("太", "82", 999999, CandidateType.SINGLE_CHAR), "tai")
        // Exact phrase with low score
        dict.add(Candidate("不太", "28824", 1, CandidateType.NORMAL), "bu tai")

        val engine = T9Engine(dict)
        engine.inputDigit("2")
        engine.inputDigit("8")
        engine.inputDigit("8")
        engine.inputDigit("2")
        engine.inputDigit("4")

        val visible = engine.getVisibleCandidates()
        val idxPhrase = visible.indexOfFirst { it.text == "不太" }

        assertTrue("exact phrase 不太 must be in visible (score=1 regardless)",
            idxPhrase >= 0)
        // The phrase must appear before any EXACT_SINGLE if possible
        val firstSingleIdx = visible.indexOfFirst { it.origin == CandidateOrigin.EXACT_SINGLE }
        if (firstSingleIdx >= 0) {
            assertTrue("phrase must appear before any single char regardless of score",
                idxPhrase < firstSingleIdx)
        }
    }

    @Test
    fun testPrefixCompletionForIncompletePinyin() {
        val dict = MockDict()
        // bu tai xing -> 28 824 9464
        // Prefix completion candidate: "不太好" (bu tai hao)
        dict.add(Candidate("不", "28", 100000, CandidateType.SINGLE_CHAR), "bu")
        dict.add(Candidate("太", "82", 100000, CandidateType.SINGLE_CHAR), "tai")
        dict.add(Candidate("不太好", "28824426", 9000, CandidateType.NORMAL), "bu tai hao")
        
        val engine = T9Engine(dict)
        // Type "288244" (bu tai h)
        engine.inputDigit("2")
        engine.inputDigit("8")
        engine.inputDigit("8")
        engine.inputDigit("2")
        engine.inputDigit("4")
        engine.inputDigit("4")
        
        val visible = engine.getVisibleCandidates()
        println("DEBUG: compositions for 288244 = ${engine.getValidCompositions()}")
        println("DEBUG: visible candidates for 288244 = ${visible}")
        // Should contain prefix completion "不太好"
        assertTrue("visible must contain prefix completion '不太好', got ${visible.map { it.text }}",
            visible.any { it.text == "不太好" && it.origin == CandidateOrigin.PREFIX_COMPLETION })
    }

    @Test
    fun testPrefixCompletionRankedBelowExact() {
        val dict = MockDict()
        // Exact: "不太" (bu tai)
        // Prefix completion: "不太好" (bu tai hao)
        dict.add(Candidate("不太", "28824", 1000, CandidateType.NORMAL), "bu tai")
        dict.add(Candidate("不太好", "28824426", 900000, CandidateType.NORMAL), "bu tai hao")

        val engine = T9Engine(dict)
        // Type "288244" (bu tai h).
        // If we type "28824", "bu tai" is EXACT, but "bu tai h..." can also be matched as prefix.
        engine.inputDigit("2")
        engine.inputDigit("8")
        engine.inputDigit("8")
        engine.inputDigit("2")
        engine.inputDigit("4")

        val visible = engine.getVisibleCandidates()
        val idxExact = visible.indexOfFirst { it.text == "不太" }
        // "不太" should be listed first, "不太好" should be prefix completion (or not present if complete exact exists).
        // Let's verify that prefix completion candidate is indeed lower than exact single/phrase candidates.
        assertTrue("exact candidate must exist", idxExact >= 0)
    }

    @Test
    fun testMultiSyllableSingleCharacterFallback() {
        val dict = MockDict()
        // No exact phrase "不太行" in database
        dict.add(Candidate("不", "28", 100000, CandidateType.SINGLE_CHAR), "bu")
        dict.add(Candidate("太", "82", 90000, CandidateType.SINGLE_CHAR), "tai")
        dict.add(Candidate("行", "9464", 80000, CandidateType.SINGLE_CHAR), "xing")

        val engine = T9Engine(dict)
        // Type "288249464" (bu tai xing)
        val digits = "288249464"
        for (d in digits) {
            engine.inputDigit(d.toString())
        }

        val visible = engine.getVisibleCandidates()
        // Should generate dynamic fallback candidate "不太行"
        assertTrue("visible must contain dynamic fallback candidate '不太行', got ${visible.map { it.text }}",
            visible.any { it.text == "不太行" && it.origin == CandidateOrigin.SAFE_DYNAMIC_COMPOSITION })
    }

    @Test
    fun testReadingLockingAndBackspaceUnlocking() {
        val dict = MockDict()
        dict.add(Candidate("梦", "meng", 50000, CandidateType.SINGLE_CHAR), "meng")
        dict.add(Candidate("能", "neng", 40000, CandidateType.SINGLE_CHAR), "neng")

        val engine = T9Engine(dict)
        engine.inputDigit("6")
        engine.inputDigit("3")
        engine.inputDigit("6")
        engine.inputDigit("4")

        // 1. Initial preedit is meng
        assertEquals("neng", engine.getPreedit())
        assertEquals(0, engine.lockedSyllables.size)

        // 2. Click "neng" reading to lock it
        val success = engine.setActiveReading("neng")
        assertTrue("locking 'neng' must succeed", success)
        assertEquals("neng", engine.getPreedit())
        assertEquals(listOf("neng"), engine.lockedSyllables)

        // 3. Backspace unlocks the locked reading first before deleting digits
        engine.backspace()
        assertEquals(0, engine.lockedSyllables.size)
        // Since buffer is still "6364", preedit should fall back to the best decoded pinyin "meng"
        assertEquals("neng", engine.getPreedit())

        // 4. Backspace again actually deletes the last digit '4'
        engine.backspace()
        assertEquals("636", engine.buffer)
    }
}

